[colors]
draw_bold_text_with_bright_colors = false

[keyboard]
bindings = [
  { key = "N", mods = "Command | Shift", action = "SpawnNewInstance" },
  { key = "W", mods = "Command", action = "Hide" },
  { key = "T", mods = "Command", action = "CreateNewTab" },
  { key = "N", mods = "Command", action = "CreateNewWindow" },
  { key = "[", mods = "Command", action = "SelectPreviousTab" },
  { key = "]", mods = "Command", action = "SelectNextTab" },
  { key = "1", mods = "Command", action = "SelectTab1" },
  { key = "2", mods = "Command", action = "SelectTab2" },
  { key = "3", mods = "Command", action = "SelectTab3" },
  { key = "4", mods = "Command", action = "SelectTab4" },
  { key = "5", mods = "Command", action = "SelectTab5" },
  { key = "6", mods = "Command", action = "SelectTab6" },
  { key = "7", mods = "Command", action = "SelectTab7" },
  { key = "8", mods = "Command", action = "SelectTab8" },
  # vi_mode
  { key = "i", mods = "Command | Shift", action = "ToggleViMode" },
  { key = "9", mode = "Vi", action = "FirstOccupied" },
  { key = "0", mode = "Vi", action = "Last" },
  { key = "o", mode = "Vi", action = "Open" },
]

[general]
live_config_reload = true

[colors.bright]
black = "#4d4d4d"
blue = "#a277ff"
cyan = "#61ffca"
green = "#61ffca"
magenta = "#a277ff"
red = "#ff6767"
white = "#edecee"
yellow = "#ffca85"

[colors.cursor]
cursor = "#a277ff"

[colors.normal]
black = "#110f18"
blue = "#a277ff"
cyan = "#61ffca"
green = "#61ffca"
magenta = "#a277ff"
red = "#ff6767"
white = "#edecee"
yellow = "#ffca85"

[colors.primary]
background = "#15141b"
foreground = "#edecee"

[colors.search.focused_match]
background = "#9F7AF5"
foreground = "#ffffff"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[colors.selection]
background = "#29263c"
text = "CellForeground"

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[font]
size = 15.0

[font.italic]
family = "CommitMono Nerd Font"
style = "Italic"

[font.normal]
family = "CommitMono Nerd Font"
style = "Regular"

[font.bold]
family = "CommitMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CommitMono Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 8

[scrolling]
history = 100000
multiplier = 4

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[window]
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"

[window.dimensions]
columns = 106
lines = 25

[window.position]
x = 800
y = 400

#
[window.padding]
x = 15
y = 22
